app/routes.php
<?php
Event::listen('Universal.Creation.Events.TenantCreated','NotificationsController@store');
Event::listen('Universal.Creation.Events.RentPaid','RentPaysController@store');
Event::listen('Universal.Creation.Events.DailyPaid','RentPaysController@store');
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');
Route::resource('/','WelcomeController');
Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');
Route::get('download',function(){
	$file = $_GET['file'];
	return Response::download($file);
});
Route::get('view', function()
{
	$file = $_GET['file'];
	return Redirect::to($file);
});

// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){
// dev
Route::resource('admin','AdminController');
Route::resource('admin.staffs','StaffsController');
Route::resource('admin.plots','PlotsController');
Route::resource('plots','PlotsController');
Route::resource('agents','AgentsController');
Route::resource('staffs','StaffsController');
Route::resource('payments','PaymentsController');
Route::resource('customers.payments','PaymentsController');
Route::resource('cocuments', 'DocumentsController');
Route::resource('customers', 'CustomersController');
Route::resource('agents.customers', 'CustomersController');
Route::resource('search', 'SearchController');
Route::resource('partners', 'PartnersController');


Route::get('transactions/checkdate',array('as'=>'checkdate','uses'=>'TransactionsController@getCheckdate'));
Route::resource('transactions', 'TransactionsController');

Route::resource('paying', 'DailyTransactionsController');
Route::resource('prospectives', 'ProspectivesController');

Route::get('tenants/vacate/{id}/{hid}',array('as'=>'vacate','uses'=>'TenantsController@getVacate'));
Route::get('tenants/kill/{id}',array('as'=>'kill','uses'=>'TenantsController@getKill'));
Route::resource('tenants.rents-paid','TenantsController@getRents');
Route::resource('tenants', 'TenantsController');

Route::resource('tenants.payments', 'TenanPaymentsController');

Route::resource('land-lords.rents-paid','LandlordsController@getRents');
Route::resource('land-lords', 'LandlordsController');

Route::resource('compounds', 'CompoundsController');
Route::resource('houses', 'HousesController');
Route::resource('notifications', 'NotificationsController');
Route::get('data-entry', array('as'=>'data_entry', 'uses'=>'PagesController@showData'));
Route::resource('estates', 'EstatesController');
Route::resource('estates.plots', 'EstatesController');
Route::resource('rent-pays', 'RentPaysController');
Route::resource('luwas', 'LuwasController');
});
#THIS IS THE TESTING PART BELOW
// Event::listen('illuminate.query',function($query){
// echo '<pre style="margin:200px 80px">';
// print_r($query);
// echo '</pre>';
// });

// DEV

Route::resource('users','UsersController');

app/views/__partials/add-to-house.blade.php
<!-- Modal -->

<div id="add-to-house" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Add to a house</h3>
  </div>
				{{Form::open( ['route'=> ['tenants.update', $tenant['tent_id'] ] ,'method'=>'PATCH'],['class'=>'form-snippet'] ) }}
					<div class="level name">
							<div>
								{{Form::label('hous_id','Select House')}}
								<select name="hous_id" class="span8">
								<?php if (!empty($newhouse)): ?>
									<?php foreach ($newhouse as $key => $house): ?>
										<option value="{{$house['hous_id']}}">{{$house['hous_number']}}</option>
									<?php endforeach ?>
									<?php else: ?>
									<option value="0">Not Available</option>
								<?php endif ?>
								</select>
								{{Form::hidden('house_add',28)}}
							</div>
					</div>


			<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
					<button class="btn btn-primary" name="createUser">Save changes</button>
			</div><!-- end of modal footer -->		
	 {{Form::close()}}
		  </div>

app/views/__partials/breadcrumb.blade.php
<nav class="breadcrumbs">
    <ol class="breadcrumb">
      <li><a href="#">Home</a></li>
      <li><a href="#">Library</a></li>
      <li class="actisve">Data</li>
    </ol>
</nav>

app/views/__partials/fetch.blade.php
           <div class="fetcher row">
                <nav class="navbar">
                    <div class="container-fluid">
                        <div id="navbar" class="navbar-collapse">
                             <ul class="nav navbar-nav">
                                  <li>
                                    <a href="#" id="checker">checking</a>
                                  </li>
                                  <li class="searcher">
                                    <form action="" method="get" class="navbar-form">
                                      <input type="text" name="q" placeholder="search here ..." autofocus>
                                       <button class="octicon octicon-search"></button>
                                    </form>
                                  </li>
                                  <li>
                                    <a href="#"><span class="octicon octicon-zap"></span></a>
                                  </li>
                                  <li>
                                    <a href="#"><span class="octicon octicon-dashboard"></span> <span class="badge">42</span></a>
                                  </li>
                            </ul> 
                        </div>                         
                    </div>
                </nav> 
                              <div class="popover bottom" id="check">
                                    <div class="arrow"></div>
                                    <h3 class="popover-title">Checking</h3>

                                    <div class="popover-content">
<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-justified" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Plot</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Customer</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Tenant</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
      
      <form method="POST" action="http://solid.dev.app/page/fetch" accept-charset="UTF-8">
        <hr>
        <div class="form-group">
          <label class="sr-only" for="exampleInputAmount">PLOT NUMBER (enter to search)</label>
          <div class="input-group">
            <div class="input-group-addon">Plot # </div>
            <input type="text" class="form-control" placeholder="plot numbers">
          </div>
        </div>
        <hr>
        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Get Customer</button>
          <button class="cancel btn" data-type="checking" data-containerid="studentChecker">Cancel</button>
        </div>
      </form>      

    </div>
    <div role="tabpanel" class="tab-pane" id="profile">
          <form method="POST" action="http://solid.dev.app/page/find" accept-charset="UTF-8" class="form-inline">
            <hr> <label class="clearfix">Customer Name :</label>
            <div class="form-group">
             
              <div class="sek">
                <div class="input-group">
                  <div class="input-group-addon">First </div>
                  <input  placeholder="name here" name="pers_fname" type="text" class="form-control">
                </div>            
              </div>

              <div class="sek">
                <div class="input-group">
                  <div class="input-group-addon">Middle </div>
                  <input  placeholder="name here" name="pers_mname" type="text" class="form-control">
                </div>            
              </div>


              <div class="sek">
                <div class="input-group">
                  <div class="input-group-addon">last </div>
                  <input  placeholder="name here" name="pers_lname" type="text" class="form-control">
                </div>            
              </div>

            </div>
            <hr><label class="clearfix">Plot Details :</label>
            <div class="form-group">
              
              <div class="sek">
                <div class="input-group">
                  <div class="input-group-addon">Area </div>
                  <input  placeholder="name here" name="pers_fname" type="text" class="form-control">
                </div>            
              </div>

              <div class="sek">
                <div class="input-group">
                  <div class="input-group-addon">Location </div>
                  <input  placeholder="name here" name="pers_mname" type="text" class="form-control">
                </div>            
              </div>


            </div>
            <hr>                
            <div class="form-actions">
              <button type="submit" class="btn btn-primary">Get Plot</button>
              <button class="cancel btn" data-type="checking" data-containerid="studentChecker">Cancel</button>
            </div>
          </form>
    </div>
    <div role="tabpanel" class="tab-pane" id="messages">
      <form method="POST" action="http://solid.dev.app/page/tenant" accept-charset="UTF-8" class="form-inline">

            <hr><label class="clearfix">Tenant Name :</label>
            <div class="form-group">
              
              <div class="sek">
                <div class="input-group">
                  <div class="input-group-addon">First </div>
                  <input  placeholder="name here" name="pers_fname" type="text" class="form-control">
                </div>            
              </div>

              <div class="sek">
                <div class="input-group">
                  <div class="input-group-addon">Middle </div>
                  <input  placeholder="name here" name="pers_mname" type="text" class="form-control">
                </div>            
              </div>


              <div class="sek">
                <div class="input-group">
                  <div class="input-group-addon">last </div>
                  <input  placeholder="name here" name="pers_lname" type="text" class="form-control">
                </div>            
              </div>

            </div>
          <hr>

            <div class="form-group">
              
              <div class="input-group">
                <div class="input-group-addon">House # </div>
                <input type="text" placeholder="Enter the house number" name="hous_number"  class="form-control col-sm-7 control-label">
              </div>
            </div>
            <hr>
        <div class="form-actions">
        <button type="submit" class="btn btn-primary">Get Tenant</button>
        <button class="cancel btn" data-type="checking" data-containerid="studentChecker">Cancel</button>
        </div>
      </form>
    </div>
  </div>

</div>

                                    </div>
                              </div>          
            </div>

app/views/__partials/modal-add-acustomer.blade.php
<!-- Modal -->

<div id="add-Acustomer" class="modal hide fade span10" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Pick a plot</h3>
  </div>
				{{Form::open(['route'=>'customers.store', 'files' => true],[],['class'=>'form-snippet'])}}

					<div class="">

						<div class="first">
							<div>
								{{Form::label('person[fname]','First Name')}}
								{{Form::text('person[fname]',null,['class'=>'span3','placeholder'=>'Enter first name','required'=>1])}}
							</div>
							<div>
								{{Form::label('person[mname]','Middle Name')}}
								{{Form::text('person[mname]',null,['class'=>'span3','placeholder'=>'Enter middle name'])}}
							</div>
							<div>
								{{Form::label('person[lname]','Last Name')}}
								{{Form::text('person[lname]',null,['class'=>'span3','placeholder'=>'Enter last name','required'=>1])}}
							</div>							
						</div>
					</div>
					<div class="level details">
						<span>Bio </span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('person[dob]','Birthday')}}
								{{Form::date('person[dob]',['class'=>'span3','placeholder'=>'Enter admission date','required'=>1])}}
							</div>

							<div>
								{{Form::label('person[Pers_Nationality]','Nationality')}}
								<select name="person[Pers_Nationality]" id="nation" class="span3">
									<?php $countries = Variable::domain('Country')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select>
							</div>
							<div>
								{{Form::label('person[Pers_Gender]','Gender')}}
								{{Form::select('person[Pers_Gender]', array('male' => 'Male','female' => 'Female'));}}
							</div>
						</div>
					</div>
					<div class="level details">
						<span>Address</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('address[Addr_Town]','Town')}}
								{{Form::text('address[Addr_Town]',null,['class'=>'span3','placeholder'=>'Enter town'])}}
							</div>
							<div>
								{{Form::label('address[Addr_District]','District')}}
								<select name="address[Addr_District]" id="region">
									<?php $countries = Variable::domain('Addr_District')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select> 
							</div>
							<div>
								{{Form::label('address[Addr_AddressStreet]','street')}}
								{{Form::text('address[Addr_AddressStreet]',null,['class'=>'span3','placeholder'=>'Enter street'])}}
							</div>
						</div>
					</div>
					<div class="level details">
						<span>Contact</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('contact[phones]','Phones')}}
								{{Form::text('contact[phones]',null,['class'=>'span3','placeholder'=>'Enter phone number(S)'])}}
							</div>
							<div>
								{{Form::label('contact[email]','Email')}}
								{{Form::text('contact[email]',null,['class'=>'span3','placeholder'=>'Enter Email address'])}} 
							</div>
							<div>
								{{Form::label('contact[telephone]',' Telephone (land line)')}}
								{{Form::text('contact[telephone]',null,['class'=>'span3','placeholder'=>'Enter numbers'])}}
							</div>
						</div>
					</div>
					<div class="level details">
						<span>Plot details</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('plotID','Plot number')}}
								<select name="cust[cust_plotID]">
								<?php if (!empty($plots)): ?>
									<?php foreach ($plots as $key => $plot): ?>
										<option value="{{$plot['plot_id']}}">{{$plot['plot_number']}}</option>
									<?php endforeach ?>
									<?php else: ?>
									<option value="0">Not Available</option>
								<?php endif ?>
								</select>
								
							</div>
							<div>
								{{Form::label('cust[cust_downpayment]','Down payment')}}
								{{Form::number('cust[cust_downpayment]',null,['class'=>'span3','placeholder'=>'Enter down payment in dalasis','required'=>1,'step'=>'any'])}} 
							</div>
							<div>
								{{Form::label('cust[period]','Period in month')}}
								{{Form::number('cust[period]',null,['class'=>'span3','placeholder'=>'Enter period in months','required'=>1])}} 
							</div>
						</div>
					</div>
					<div class="level details">
						<span>Payment details</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('cust[pay_commencing]','Commencing')}}
								{{Form::date('cust[pay_commencing]',['class'=>'span3 span6','placeholder'=>'Enter date the payments should start'])}} 
							</div>
							<div>
								{{Form::label('cust[pay_type]','Payment Type')}}
								{{Form::select('cust[pay_type]',['cash'=>'cash','mortgage'=>'mortgage'])}} 
							</div>
						</div>
					</div>
					<div class="level details">
						<span>Identification details</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('person[nin_id]','Nation id number / passport number')}}
								{{Form::text('person[nin_id]',null,['class'=>'span3 span6','placeholder'=>'NIN number or passport number'])}} 
							</div>
							<div>
								{{Form::label('photo','Photo')}}
								{{Form::file('photo')}}
							</div>	
							<div>
								{{Form::label('document','Land Document')}}
								{{Form::file('document')}}
							</div>
						</div>
					</div>
					<div class="level details">
						<span>Next of Kin</span>
						<hr>

						<div class="first">
							<div>
								{{Form::label('kin[fname]','First Name')}}
								{{Form::text('kin[fname]',null,['class'=>'span3','placeholder'=>'Enter first name'])}}
							</div>
							<div>
								{{Form::label('kin[mname]','Middle Name')}}
								{{Form::text('kin[mname]',null,['class'=>'span3','placeholder'=>'Enter middle name'])}}
							</div>
							<div>
								{{Form::label('kin[lname]','Last Name')}}
								{{Form::text('kin[lname]',null,['class'=>'span3','placeholder'=>'Enter last name'])}}
							</div>	
							<div>
								{{Form::label('kin[contact]','Contacts')}}
								{{Form::text('kin[contact]',null,['class'=>'span3','placeholder'=>'Enter contact details'])}}
							</div>						
						</div>
					</div>

			<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
					<button class="btn btn-primary" name="createUser">Save changes</button>
			</div><!-- end of modal footer -->		
	 {{Form::close()}}
		  </div>

app/views/__partials/modal-add-estate.blade.php
<!-- Modal -->

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Add a new Estate</h3>
  </div>
  {{Form::open(['route'=>'estates.store'],[],['class'=>'form-snippet'])}}
		  <div class="modal-body">
				
					<div class="level name">

						<div>
							{{Form::label('est_name','Estate name')}}
							{{Form::text('est_name',null,['class'=>'input-xlarge span6','placeholder'=>'Enter estate name'])}}
						</div>
						<div>
							{{Form::label('est_location','Location')}}
							{{Form::text('est_location',null,['class'=>'input-xlarge span6','placeholder'=>'Enter location'])}}
						</div>
					</div>
		  </div>
			<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
					<button class="btn btn-primary" name="createUser">Save changes</button>
			</div><!-- end of modal footer -->		
	 {{Form::close()}}
</div>

app/views/__partials/modal-add-house.blade.php
<!-- Modal -->

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Add a new house</h3>
  </div>
{{Form::open(['route'=>'houses.store'],[],['class'=>'form-snippet'])}}
		  <div class="modal-body">
				
					<div class="level name">

						<div>
							{{Form::label('house_number','House number')}}
							{{Form::text('house_number',null,['class'=>'input-xlarge span6','placeholder'=>'House Number'])}}
						</div>
						<div>
							{{Form::label('room_number','Number of rooms')}}
							{{Form::number('room_number',null,['class'=>'input-xlarge span6','placeholder'=>'number of rooms','step'=>'any'])}}
						</div>
					</div>
					<div class="level name">
						<div>
							{{Form::label('house_price','Price')}}
							{{Form::text('house_price',null,['class'=>'input-xlarge span6','placeholder'=>'House price per month'])}}
						</div>
						<div>
							{{Form::label('house_advance','Advance Amount')}}
							{{Form::number('house_advance',null,['class'=>'input-xlarge span6','placeholder'=>'Advance payment','step'=>'any'])}}
						</div>
					</div>
					<div class="level name">
						<div>
							{{Form::label('house_compound','Compound')}}
							<select class="span6" name="house_compound">
								<option value="0">compounds</option>
								<?php
								 $comps = Compound::all();
								 $compounds = ($comps)? $comps->toArray() : [];
								  ?>
								<?php foreach ($compounds as $key => $value): ?>
									<option value="{{$value['comp_id']}}">
										{{$value['comp_indentifier']}}
									</option>
								<?php endforeach ?>
							</select>
						</div>


					</div>
					<div class="level">
						<div>
							{{Form::label('house_descriptions','Description')}}
							{{Form::textarea('house_remarks',null,['class'=>'input-xlarge span6','placeholder'=>'Enter your Description here'])}}
						</div>
					</div>

			</div>
			<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
					<button class="btn btn-primary" name="createUser">Save changes</button>
			</div><!-- end of modal footer -->		
	 {{Form::close()}}
		  </div>

app/views/__partials/sub-menu.blade.php
<div class="acctheda  fixheda_style">
	<div class="navbar">
		<div class="navbar-inner">
			<div class="hedacont">	
			    <a class="active brand blr" href="#" id="menu" title="click here to see a navigation"><i class="fa fa-bars"></i></i>MENU</a>
			    <ul class="nav">
				      <li><a href="{{route('land-lords.create')}}" title="add a land lord"><i class="fa fa-plus"></i> Land Lord</a></li>
				      <li><a href="{{route('compounds.create')}}" title="add a Compound"><i class="fa fa-plus"></i> Compound</a></li>
				       <li><a href="{{route('plots.create')}}"><i class="fa fa-plus"></i> Add Plot</a></li>
				      <li><a href="{{route('staffs.create')}}" title="add a Hous"><i class="fa fa-plus"></i> Staff</a></li>
				      <!-- <li><a href="{{route('payments.create')}}">Add Payment</a></li> -->
				      <li class="blr">
				      	<a href="#" id="checker">Checking</a>
				      </li>
			    </ul>
			    <div class="popover fade bottom in" id="studentChecker">
			      	<div class="arrow"></div>
			      	<h3 class="popover-title">Checking For A Customer</h3>
			      	<div class="popover-content">
						<div class="tabbable"> <!-- Only required for left/right tabs -->
							<ul class="nav nav-tabs">
							    <li class="active"><a href="#tab1" data-toggle="tab">Plot Number</a></li>
							    <li><a href="#tab2" data-toggle="tab">Customer Details</a></li>
							    <li><a href="#tab3" data-toggle="tab">Tenant</a></li>
							</ul>
							<hr>
							<div class="tab-content">
								<div class="tab-pane active" id="tab1">
						      			{{Form::open(array('action'=>'PagesController@postFetch','method'=>'POST'))}}
						      				<div class="input-prepend">
											  <span class="add-on">Plot#</span>
											  {{Form::text('plot_number',null,['class'=>"span6",'placeholder'=>"Plot Number",'required'=>1])}}
											</div>
										<div class="form-actions">
										  <button type="submit" class="btn btn-primary">Get Customer</button>
										  <button  class="cancel btn" data-type="checking" data-containerid="studentChecker">Cancel</button>
										</div>
						      			{{Form::close()}}
								</div>
								<div class="tab-pane" id="tab2">
						      		{{Form::open(array('action'=>'PagesController@postFind','method'=>'POST'))}}
					      				<div class="input-prepend">
					      					<label>Customer Name :</label>
										  	<span class="add-on">First</span>
										  	{{Form::text('pers_fname',null,['class'=>"span2", 'placeholder'=>"name here"])}}
										 	<span class="add-on">Middle</span>{{Form::text('pers_mname',null,['class'=>"span2", 'placeholder'=>"name here"])}}
											<span class="add-on">last</span>{{Form::text('pers_lname',null,['class'=>"span2", 'placeholder'=>"name here"])}}
										</div>
										<hr>
						      			<label>Plot Details :</label>
						      			<div class="input-prepend">
											<span class="add-on">Area</span>
											{{Form::text('plot_size',null,['class'=>"span2", 'placeholder'=>"Enter the land size"])}}
										</div>
						      			<div class="input-prepend">
											<span class="add-on">Location</span>
											{{Form::text('plot_location',null,['class'=>"span2", 'placeholder'=>"PLot address or location"])}}
										</div>
										<div class="form-actions">
											  <button type="submit" class="btn btn-primary">Get Plot</button>
											  <button  class="cancel btn" data-type="checking" data-containerid="studentChecker">Cancel</button>
										</div>
						      		{{Form::close()}}
								</div>
								<div class="tab-pane" id="tab3">
						      			{{Form::open(array('action'=>'PagesController@postTenant','method'=>'POST'))}}
						      				<div class="input-prepend">
						      					<label>Tenant Name :</label>
											  	<span class="add-on">First</span>
											  	{{Form::text('pers_fname',null,['class'=>"span2", 'placeholder'=>"name here"])}}
											 	<span class="add-on">Middle</span>{{Form::text('pers_mname',null,['class'=>"span2", 'placeholder'=>"name here"])}}
												<span class="add-on">last</span>{{Form::text('pers_lname',null,['class'=>"span2", 'placeholder'=>"name here"])}}
											</div>
											<hr>
						      				<label>House Details :</label>
						      				<div class="input-prepend">
											  	<span class="add-on">House#</span>
											  	{{Form::text('hous_number',null,['class'=>"span2", 'placeholder'=>"Enter the house number"])}}
											</div>
											<div class="form-actions">
											  	<button type="submit" class="btn btn-primary">Get Tenant</button>
											  	<button class="cancel btn" data-type="checking" data-containerid="studentChecker">Cancel</button>
											</div>
						      			{{Form::close()}}
								</div>
							</div>
						</div>
	      			</div>
			    </div>
			    {{Form::open(array('route'=>'search.index','method'=>'get'))}}
					<div class="input-append">
						{{ Form::text('q',null,['class'=>'span5','placeholder'=>"seach here",'id'=>"appendedInputButtons",'required'=>1]) }}
						{{ Form::hidden('x',1) }}	
					  	<button class="btn" type="submit" name="type" value="natural">Search</button>
					  	<!-- <button class="btn" type="submit" name="type" value="index">Extreme Search</button> -->
					</div>
				{{Form::close()}}
			</div>
		</div> <!--navbar-inner-->
	</div><!--navbar -->	
</div> <!--acctheda -->
<div class="sidebar">
	<ul>
        <li><a href="{{route('admin.index')}}" class="ui-link"><i class="fa fa-chevron-circle-left"></i>Add Menu</a></li>
        <li><a href="{{route('customers.create')}}" class="ui-link"><i class="fa fa-plus"></i>Customers</a></li>
        <li><a href="{{route('agents.create')}}" class="ui-link"><i class="fa fa-plus"></i>Agents</a></li>
        <!-- <li><a href="{{route('staffs.create')}}" class="ui-link"><i class="fa fa-plus"></i>Staff</a></li> -->
        <!-- <li><a href="{{route('prospectives.create')}}" class="ui-link"><i class="fa fa-plus"></i>Prospectives</a></li> -->
        <!-- <li><a href="{{route('compounds.create')}}" class="ui-link"><i class="fa fa-plus"></i>Compound</a></li> -->
        <!-- <li><a href="{{route('land-lords.create')}}" class="ui-link"><i class="fa fa-plus"></i>Land Lord</a></li> -->
        <li><a href="{{route('tenants.create')}}" class="ui-link"><i class="fa fa-plus"></i>Tenant</a></li>
        <li><a href="{{route('houses.create')}}" class="ui-link"><i class="fa fa-plus"></i>House</a></li>
<!-- 					        <li><a href="#" class="ui-link"><i class="fa fa-shopping-cart"></i> Businesses</a></li>
        <li><a href="#" class="ui-link"><i class="fa fa-music"></i>Entertainment</a></li>
         -->
        <li><a href="#" class="ui-link"><i class="fa fa-cog"></i> Settings</a></li>
    </ul>
</div> <!--sidebar-->